openapi: 3.0.3
info:
  version: 1.0.0
  title: Tap To Snap API
tags:
  - name: item
servers:
  - url: https://taptosnap.nonprod.kube.lab49cloud.com/v1
paths:
  /item/list:
    $ref: "item.yaml#/paths/~1item~1list"
  /item/image:
    $ref: "item.yaml#/paths/~1item~1image"
