/**
 * Tap To Snap API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.lab49.taptosnap.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 *
 * @param imageLabel 
 * @param image 
 */

data class UploadImagePayload (

    @Json(name = "imageLabel")
    val imageLabel: kotlin.String,

    @Json(name = "image")
    val image: kotlin.String

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

